BOT_TOKEN: 
  - MTAyMzIzNTg1MTE5NjU3OTg5MA.GOT2-D.ldiUf_SGwW9jSKj-VF9Es4XcccxV7-ZotcRp0E
  
CHANNEL_ID: 
  - 1060552057230213193
  
MODE: simsimi
REPLY: Y
SIMSIMI_LANG: en
DELAY: 15
DEL_AFTER: 
REPOST_LAST_CHAT: 100
